blueprint:
  name: Switch auto-off timer
  description: When a switch is turned on - auto turn off after a specified duration
  domain: automation
  input:
    switch:
      name: EntitySelect
      description: The switch/plug you want to have turn off after a set time
      selector:
        entity:
          domain: switch
    switch_2:
      selector:
        entity:
    on_duration:
      name: When turned on, how long before auot-turned off
      selector:
        number:
          min: 1
          max: 600

mode: single
# trigger:
#   - platform: device
#     type: turned_on
#     device_id:
#     domain: switch

# trigger:
#   - platform: device

#     # entity: !input switch
#     # to: 'on'
#     # for:
#     #   minutes: !input on_duration

# action:

#   service: switch.turn_off
#   entity_id: !input switch
