---
blueprint:
  name: Fireplace ðŸ”¥ï¸ Sounds ðŸŽ¶ï¸
  description: >
    This blueprint will let you tie together a speaker(s) and a fireplace so you can get nice fireplace sounds when the fire is on
  domain: automation
  input:
    fireplace_sensor:
      name: Fireplace Sensor
      description: Sensor that has the on/off state of the fireplace
      selector:
        entity:
          filter:
            domain:
              - binary_sensor
              - input_boolean
    player:
      name: Where to play fireplace sounds
      selector:
        entity:
          filter:
            domain:
              - media_player
    start_vol:
      name: Volume settings
      description: At what volume should the fire sound play
      selector:
        number:
          min: 0
          max: 1
          step: .1
      default: .27
    end_vol:
      name: Volume settings
      description: What level do you wish to return the volume to after you stop playing the fire sounds.
      selector:
        number:
          min: 0
          max: 1
          step: .1
      default: .27

    media:
      name: Select a sound
      description: Due to limitations in HA you will also have to re-select the media player above
      selector:
        media:
mode: queued

variables:
  fireplace_sensor: !input fireplace_sensor
  fireplace_state: "{{states(fireplace_sensor)}}"
  is_fireplace_on: "{{is_state(fireplace_sensor,'on')}}"

  media: !input media
  player: !input player
  start_vol: !input start_vol
  end_vol: !input end_vol
  fire_content_id: "{{ media['media_content_id']  }}"
  fire_content_substr: "{{ media['media_content_id']  | replace('media-source://media_source/','') }}"
  current_content_id: "{{ state_attr(player,'media_content_id') }}"
  is_fire_sound: >
    {%- if current_content_id %}
    {{ fire_content_substr in current_content_id }}
    {%- else %}
    {{ false }}
    {%- endif %}

  is_playing: "{{is_state(player,'playing')}}"
  is_playing_fire_sound: "{{ is_playing and is_fire_sound}}"
  action_to_take: >-
    {%- if is_fireplace_on and not is_playing %}
      {%- if trigger.id == 'stopped' and is_fire_sound %}
      do_nothing
      {%- else %}
      play_music
      {%- endif %}
      {#- If fireplace is off and we were playing the fire music -#}
      {%- elif not is_fireplace_on and (is_playing and is_fire_sound) %}
      stop_music
      {%- else %}
      do_nothing
    {%- endif %}

  last_state: >
    {{ trigger }}
  bool1: "{{ 'from_state' in trigger }}"
  bool2: "{{ 'entity_id' in trigger }}"
  bool3: "{{ 'id' in trigger }}"
  bool4: "{{ 'to_state' in trigger }}"

  dev: >
    {%- if 'from_state' in trigger -%}
      From: {{trigger.from_state}}  
    {%- endif -%}
    {%- if 'to_state' in trigger -%}
      To: {{trigger.to_state}}  
    {%- endif -%}
trigger:
  - trigger: state
    entity_id: !input fireplace_sensor
    id: fireplace_state
  - trigger: state
    # Stop playing Music
    entity_id: !input player
    id: music_stop
    from: "playing"
    for:
      seconds: 1
  # - platform: time_pattern
  #   id: time_pattern
  #   seconds: /5
  # minutes: /5
  # - platform: state
  #   # Start playing music... not sure why i need this one?
  #   entity_id: !input player
  #   id: media_start
  #   to: "playing"

# Don't do anything for do_nothing
condition: []

action:
  # Debug stuff
  - action: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "dev"
      payload: >
        bool1: {{bool1}}
        bool2: {{bool2}}
        bool3: {{bool3}}
        bool4: {{bool4}}

  - action: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "dev"
      payload: "{{dev}}"
      # payload: "{{trigger | to_json}}"

  - choose:
      # - conditions:
      #     - condition: trigger
      #       id: stop_5_seconds
      #   sequence: []
      # # Not playing music, and the fire is on
      - conditions:
          - condition: template
            value_template: "{{action_to_take == 'play_music'}}"
        sequence:
          # Unjoin the groups
          - action: media_player.unjoin
            target:
              entity_id: "{{player}}"
          # set volume
          - action: media_player.volume_set
            data:
              volume_level: "{{start_vol}}"
            target:
              entity_id: "{{player}}"
          # play
          - action: media_player.play_media
            data:
              media_content_id: "{{fire_content_id}}"
              media_content_type: music
            target:
              entity_id: "{{player}}"
          # Repeat ON
          - action: media_player.repeat_set
            data:
              repeat: one
            target:
              entity_id: "{{player}}"

      # Stop the MUSIC
      - conditions:
          - condition: template
            value_template: "{{action_to_take == 'stop_music'}}"
        sequence:
          # Pause/Stop the current "stuff" the current
          - action: media_player.media_stop
            target:
              entity_id: "{{player}}"
          - action: media_player.volume_set
            data:
              volume_level: "{{end_vol}}"
            target:
              entity_id: "{{player}}"

      - conditions:
          - condition: template
            value_template: "{{action_to_take == 'do_nothing'}}"
        sequence: []
